import type { Metadata } from 'next';
import { DM_Sans, Syne } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import { ThemeProvider } from '@/hooks/use-theme';

const dmSans = DM_Sans({ subsets: ['latin'], variable: '--font-sans' });

const SyneHeading = Syne({ subsets: ['latin'], variable: '--font-heading' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={cn('h-full', 'antialiased', 'font-sans', dmSans.variable, SyneHeading.variable, 'dark')}>
      <body className='min-h-full flex flex-col'>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
