import type { Metadata } from 'next';
import { DM_Sans, Syne } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import { ThemeProvider } from '@/hooks/use-theme';
import { LanguageProvider } from '@/hooks/use-language';
import { LoadingProvider } from '@/hooks/use-loading';
import { LoadingOverlay } from '@/components/LoadingOverlay';

const dmSans = DM_Sans({ subsets: ['latin'], variable: '--font-sans' });

const SyneHeading = Syne({ subsets: ['latin'], variable: '--font-heading' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // `lang`, `dark` e `is-loading` são o estado inicial do SSR; os providers
    // ajustam o atributo/classe no mount. `is-loading` trava o scroll (ver
    // globals.css) e sai junto com o overlay.
    <html
      lang='pt-BR'
      className={cn(
        'h-full',
        'antialiased',
        'font-sans',
        dmSans.variable,
        SyneHeading.variable,
        'dark',
        'is-loading'
      )}
    >
      <body className='min-h-full flex flex-col'>
        <LoadingProvider>
          <LanguageProvider>
            <ThemeProvider>{children}</ThemeProvider>
          </LanguageProvider>

          <LoadingOverlay />
        </LoadingProvider>
      </body>
    </html>
  );
}
